# This workflow will do a clean install of node dependencies, 
# build the source code and run tests across different versions of node
# For more information see: 
# https://help.github.com/actions/language-and-framework-guides/using-anodejs-with-github-actions
# teest 1
name: Node.js CI

on:
  push:
    branches: ["delivery"]
  pull_request:
    branches: ["delivery"]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.18.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      
    - run: npm i
    - run: npm run build --if-present
    - run: npm run start
